name: SonarCloud Scan & Snyk Security Scan
on: [push, pull_request]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Build and Run SonarCloud Scanner
        run: |
          docker run --rm -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          -v ${GITHUB_WORKSPACE}:/usr/src \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=pyfanpage \
          -Dsonar.organization=pyfanpage \
          -Dsonar.php.coverage.reportPaths=coverage.xml \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist

      # Aquí añadimos el análisis de Snyk
      - name: Install Snyk
        run: |
          npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk monitor --file=composer.lock --package-manager=composer
          snyk test --file=composer.lock --package-manager=composer
