name: SonarCloud Scan
on: [push, pull_request]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # O la versión que estés usando
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          projectBaseDir: './'
          args: '-Dsonar.projectKey=pyfanpage -Dsonar.organization=pyfanpage'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
