name: SonarCloud Scan & Security Analysis
on: [push, pull_request]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verify Java version
        run: java -version

      - name: Build and Run SonarCloud Scanner
        run: |
          docker run --rm -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
          -v ${GITHUB_WORKSPACE}:/usr/src \
          sonarsource/sonar-scanner-cli \
          -Dsonar.projectKey=pyfanpage \
          -Dsonar.organization=pyfanpage \
          -Dsonar.php.coverage.reportPaths=coverage.xml \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io

      - name: Install Semgrep
        run: |
          pip install semgrep

      - name: Run Semgrep Scan
        run: |
          semgrep scan --config='p/default' --sarif --output=report.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif
          token: ${{ secrets.GITHUB_TOKEN }} # Token automático
