name: SonarCloud Scan
on: [push, pull_request]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Cambia a la versión que uses

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          args: '-Dsonar.projectKey=pyfanpage -Dsonar.organization=pyfanpage'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
