name: SonarCloud Scan
on: [push, pull_request]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Cambiado a PHP 8.1

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'  # Cambiado a Java 16
          distribution: 'adopt'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          projectBaseDir: './'
          args: >
            -Dsonar.projectKey=pyfanpage
            -Dsonar.organization=pyfanpage
            -Dsonar.php.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
